[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "npx prisma migrate deploy && npm run start"
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
